### ISSUE TITLE
Output sound lags

### ISSUE THREAD

**Issue by Cuda-Chen** [sysprog21/vsnd#2]
Currently, the output of `vsnd` lags (the `out.wav` generated by `script/verify.sh`) compared to the input sound (`CantinaBand3.wav`).

**Comment by Cuda-Chen** [comment]
After some experiments, I find that if we set the output sink from Settings -> Sound then play sounds will result in lagged sound outputs.

**Comment by jserv** [comment]
> After some experiments, I find that if we set the output sink from Settings -> Sound then play sounds will result in lagged sound outputs.

Can you disable PulseAudio and verify the functionality of vsnd?
I always remove this package during the development.

**Comment by Cuda-Chen** [comment]
Hi @jserv ,

Thanks for your help!
After disabling PluseAudio, the output sound does not lag anymore.
